version: '3'
services:
  main:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/home/root/project/
    tty: true
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8

